### PR TITLE
Add two story sections

### PR DESCRIPTION
**Pull request by merrittharlan**
Add "Getting Water to Your Homes" and "Dryville's First Water Works" to the story

### CODE REVIEW

**Comment by jesse-ross** [comment]
This looks good! But #5 missed a couple of links which should be in there. Could you please add the other two links from [the "Getting Water to Your Homes" section](https://www.usgs.gov/special-topics/water-science-school/science/story-water-dryville)?

**Review by jesse-ross — CHANGES_REQUESTED** [review]
Requesting minor changes

**Comment by merrittharlan** [comment]
I added the missing links, and another commit (hopefully in the correct order)- thanks for the feedback!

**Review by jesse-ross — APPROVED** [review]
Awesome! 🎉

**Pull request merged**
